<a href="https://colab.research.google.com/github/ibrohim747/pandas_exercises/blob/main/Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [ ]:
S = Series([10, 20, 30, 40, 50])
S

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
g = np.random.default_rng(0)
a = g.integers(0, 100, 10)

g = np.random.default_rng(0)
b = g.integers(0, 100, 10)

a == b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
g = np.random.default_rng(0)
s = Series(g.integers(70, 101, 10))
s

0    96
1    89
2    85
3    78
4    79
5    71
6    72
7    70
8    75
9    95
dtype: int64

In [ ]:
s.index = "Sep Oct Nov Dec Jan Feb Mar Apr May Jun".split()
s

Sep    96
Oct    89
Nov    85
Dec    78
Jan    79
Feb    71
Mar    72
Apr    70
May    75
Jun    95
dtype: int64

In [ ]:
g = np.random.default_rng(0)
month = "Sep Oct Nov Dec Jan Feb Mar Apr May Jun".split()
s = Series(g.integers(70, 101, 10), index = month)
s

Sep    96
Oct    89
Nov    85
Dec    78
Jan    79
Feb    71
Mar    72
Apr    70
May    75
Jun    95
dtype: int64

In [ ]:
print(f"Yearly average: {s.mean()}")

Yearly average: 81.0

In [ ]:
year_1 = s[:5].mean()
year_2 = s[5:].mean()
print(f"1 year average: {year_1}")
print(f"2 year average: {year_2}")

1 year average: 85.4
2 year average: 76.6

In [ ]:
first_half_year = s.loc["Sep": "Jan"].mean()    # loc = location   iloc = index location
second_half_year = s.loc["Feb": "Jun"].mean()
print(f"First half year average: {first_half_year}")
print(f"Second half year average: {second_half_year}")

First half year average: 85.4
Second half year average: 76.6

In [ ]:
head_1 = s.head(5).mean()
tail_1 = s.tail(5).mean()
print(f"First 5 months average: {head_1}")
print(f"Last 5 months average: {tail_1}")

First 5 months average: 85.4
Last 5 months average: 76.6

In [ ]:
s.max()

96

In [ ]:
s.idxmax()
print(s["Sep"])

96

In [ ]:
s.sort_values()
s[:5]

Sep    96
Oct    89
Nov    85
Dec    78
Jan    79
dtype: int64

In [ ]:
print(s.round(-1))

Sep    100
Oct     90
Nov     80
Dec     80
Jan     80
Feb     70
Mar     70
Apr     70
May     80
Jun    100
dtype: int64