<a href="https://colab.research.google.com/github/ibrohim747/pandas_exercises/blob/main/Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [ ]:
g = np.random.default_rng();
s = Series(g.integers(0, 100, 10));
s

0    18
1    47
2    42
3    45
4    95
5    74
6    86
7    18
8     3
9    19
dtype: int64

In [ ]:
s = s / 10
s

0    1.8
1    4.7
2    4.2
3    4.5
4    9.5
5    7.4
6    8.6
7    1.8
8    0.3
9    1.9
dtype: float64

In [ ]:
s = s.astype(np.int8)
s

0    1
1    4
2    4
3    4
4    9
5    7
6    8
7    1
8    0
9    1
dtype: int8

In [ ]:
s = Series(g.integers(0, 100, 10));
(
    s
    .astype(str)      #convert to string
    .str.get(-2)      #get the -2 element
    .fillna('0')      #change NaN to '0'
    .astype(np.int8)  #convert str to int8
)

0    4
1    0
2    8
3    6
4    8
5    3
6    6
7    0
8    9
9    2
dtype: int8

In [ ]:
sloc = s.loc[0: 3];
sloc

0    42
1     5
2    85
3    68
dtype: int64

In [ ]:
iloc = s.iloc[0: 3];
iloc

0    42
1     5
2    85
dtype: int64

In [ ]:
s.loc[[True, False, True, True, True, False, True, False, True, False]]

0    42
2    85
3    68
4    88
6    67
8    94
dtype: int64

In [ ]:
s = Series(g.integers(0, 100, 10));
s.loc[s < 30]

4    23
5    24
6    22
7    14
8    10
9     1
dtype: int64

In [ ]:
s.loc[s < s.mean()]

4    23
5    24
6    22
7    14
8    10
9     1
dtype: int64

In [ ]:
s = Series(g.integers(0, 100, 10));
s.loc[s <= s.mean()] = 99
s

0    99
1    97
2    99
3    99
4    85
5    99
6    49
7    99
8    78
9    99
dtype: int64

In [ ]:
s.loc[[2, 4]]  #s.loc[2] и s.loc[4]

2    99
4    85
dtype: int64